# Stage 1: Build
FROM node:18.15.0 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Stage 2: Production
FROM node:18.15.0
WORKDIR /app
COPY --from=builder /app /app
EXPOSE 5003
CMD ["npm", "start"]
