name: Docker Image Build and Push

on:
  push:
    paths:
      - 'docker-compose.yml'
      - '**/Dockerfile'
      - '01-AuthService/**'
      - '02-PatientService/**'
      - '03-AdmissionService/**'
      - '04-WardService/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'docker-compose.yml'
      - '**/Dockerfile'
      - '01-AuthService/**'
      - '02-PatientService/**'
      - '03-AdmissionService/**'
      - '04-WardService/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker images
        run: |
          docker build -t amitmakhija2308/apigateway:v3 ./api-gateway
          docker build -t amitmakhija2308/ward-service:v3 ./04-WardService
          docker build -t amitmakhija2308/admission-service:v3 ./03-AdmissionService
          docker build -t amitmakhija2308/patient-service:v3 ./02-PatientService
          docker build -t amitmakhija2308/auth-service:v3 ./01-AuthService

      - name: Push Docker images to Docker Hub
        run: |
          docker push amitmakhija2308/apigateway:v3
          docker push amitmakhija2308/ward-service:v3
          docker push amitmakhija2308/admission-service:v3
          docker push amitmakhija2308/patient-service:v3
          docker push amitmakhija2308/auth-service:v3